#! /bin/sh
set -e

if [ -x /usr/bin/gtk-update-icon-cache ]; then
    if ! gtk-update-icon-cache --force --quiet /usr/share/icons/hicolor; then
        echo "WARNING: icon cache generation failed"
    fi
fi

if [ -x /usr/bin/gtk-update-icon-cache-3.0 ]; then
    if ! gtk-update-icon-cache-3.0 --force --quiet /usr/share/icons/hicolor; then
        echo "WARNING: icon cache generation failed"
    fi
fi

if [ "$1" = "triggered" ]; then
    exit 0
fi


